import { buttonVariants } from "@/components/ui/button";
import "./globals.css";
import type { Metadata } from "next";
import { Borel, Poppins, Patrick_Hand_SC } from "next/font/google";
import Link from "next/link";
import { BsGithub, BsMoonFill } from "react-icons/bs";
import Navbar from "@/components/custom/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        <main className="py-20 overflow-y-hidden">{children}</main>
        <footer className="footer">Footer</footer>
      </body>
    </html>
  );
}
